### PR TITLE
nix: add proper nix support

### PR DESCRIPTION
**Pull request by mtrsk**
This PR adds a `flake.nix` file into this project, it also includes a dev env with LSP embed into it.

However, I didn't have the time to check the codebase yet, it seems the build it's failing because of a type mistmatch.

```shell
❯ nix build                                  
warning: input 'flake-utils' has an override for a non-existent input 'nixpkgs'
error: builder for '/nix/store/12zxa5i1gkg6zdkzcig1khbvm8d18p2d-spatula-0.1.0.0.drv' failed with exit code 1;
       last 10 log lines:
       >                          (TForall
       >                             (AbstractionInfo
       >                                "typeB"
       >                                (TArrow
       >                                   (TArrow (TVariable "typeA") (TVariable "typeB"))
       >                                   (TArrow (TVariable "typeA") (TVariable "typeB"))))))
       >             typeCheck abst `shouldBe` Right type'’
       >    |
       > 41 |         typeCheck abst `shouldBe` Right type'
       >    |                                   ^^^^^^^^^^^
       For full logs, run 'nix log /nix/store/12zxa5i1gkg6zdkzcig1khbvm8d18p2d-spatula-0.1.0.0.drv'.
```

as of now I can't compile this with a pure nix build.

if you want to test just the devenv, I've only put cabal build tools and other goodies, no stack bs. Make sure to comment the following lines:

```nix

      in rec {
        #packages.${packageName} = # (ref:haskell-package-def)
        #  haskellPackages.callCabal2nix packageName self rec {
        #    # Dependency overrides go here
        #  };

        #defaultPackage = self.packages.${system}.${packageName};

        devShell = haskellPackages.shellFor {
          #inputsFrom = builtins.attrValues self.packages.${system};
          withHoogle = true;
```
then run
```shell
nix develop
```

@MMagueta @EduardoLR10 Please let me know what is wrong with the build.

### CODE REVIEW

**Comment by EduardoLR10** [comment]
Probably the build error comes from the tests, which probably are not compiling anymore due to significant changes that we did on the code but were not reflected back to the tests.

**Comment by mtrsk** [comment]
> Probably the build error comes from the tests, which probably are not compiling anymore due to significant changes that we did on the code but were not reflected back to the tests.

Here's what I did:

1. Comment `test-suit` in `spatula.cabal`

```
--test-suite spatula-test
--  type: exitcode-stdio-1.0
--  main-is: Spec.hs
--  other-modules:
--      TestTyper
--      Paths_spatula
--  hs-source-dirs:
--      test
--  ghc-options: -Wall -Wcompat -Widentities -Wincomplete-record-updates -Wincomplete-uni-patterns -Wmissing-export-lists -Wmissing-home-modules -Wpartial-fields -Wredundant-constraints -threaded -rtsopts -with-rtsopts=-N
--  build-depends:
--      QuickCheck
--    , base >=4.7 && <5
--    , bytestring
--    , containers
--    , envparse
--    , haskeline >=0.8.2
--    , hspec
--    , mtl
--    , optparse-applicative
--    , parsec
--    , quickcheck-arbitrary-adt
--    , quickcheck-text
--    , random
--    , spatula
--    , terminal-size
--    , text
--    , vector
--  default-language: Haskell2010
```
2. Run `nix build`
3. Run `nix develop`

Seems to work fine

**Comment by mtrsk** [comment]
@EduardoLR10 can we merge this?

**Comment by EduardoLR10** [comment]
@mtrsk Could you add `stack` also to the tool set?

**Comment by mtrsk** [comment]
> @mtrsk Could you add `stack` also to the toolset? You can also comment the test-suite in this PR, that would be handy. Given that this is a better nix solution overall, I think we can nuke `shell.nix` also.

Ok. let me add `stack` and configure some pipelines that ignore the test cases (for now).

**Comment by mtrsk** [comment]
@EduardoLR10 Done, there is no need to modify the cabal file, since the testing suite is automatically ignored by Nix now.

**Comment by EduardoLR10** [comment]
Perfect! Thanks, @mtrsk!

**Pull request merged**
